CREATE TABLE billboard (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  storeId INT NOT NULL,
  label VARCHAR(255) NOT NULL,
  imageUrl VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (storeId) REFERENCES Store (id)
);
