CREATE TABLE Category (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	storeId INT NOT NULL,
	billboardId INT NOT NULL,
	name VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (storeId) REFERENCES Store(id),
	FOREIGN KEY (billboardId) REFERENCES Billboard(id)
);
