CREATE TABLE Product (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	storeId INT NOT NULL,
	categoryId INT NOT NULL,
	name VARCHAR(255) NOT NULL,
	price DECIMAL(10, 2) NOT NULL,
	isFeatured BOOLEAN DEFAULT FALSE,
	haveColor BOOLEAN DEFAULT FALSE,
	haveSize BOOLEAN DEFAULT FALSE,
	isArchived BOOLEAN DEFAULT FALSE,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (storeId) REFERENCES Store(id),
	FOREIGN KEY (categoryId) REFERENCES Category(id)
	);