
CREATE TABLE face (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	productId INT NOT NULL,
	faceUrl VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (productId) REFERENCES product(id)
);
	